"""Analyse proton through/PMMA or makerP runs in the reduced rat phantom.

The two configurations use the same source and beam:

* ``through``: 100 MeV without a range shifter;
* ``peak55``: 100 MeV with a 55-mm PMMA range shifter;
* ``makerP_*``: the scientific-supervisor multi-source spectrum, rigidly
  rotated from +z to the rat-phantom -y transport axis.

The beam travels along Geant4 ``-y``.  The DICOM GTVp contour is rasterised
onto the 0.4 x 0.4 x 0.2 mm scoring grid.  Absolute doses are the doses
generated by the stated number of simulated primaries, not prescribed
experimental doses.  Dimensionless DVH ratios are therefore also reported.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
import re
import struct
import sys

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image, ImageDraw


NEURO_STATS_ROOT = Path(__file__).resolve().parents[3]
if str(NEURO_STATS_ROOT) not in sys.path:
    sys.path.insert(0, str(NEURO_STATS_ROOT))

TASK_DIR = Path(r"C:\dev\dissertation\task4_5")
if str(TASK_DIR) not in sys.path:
    sys.path.insert(0, str(TASK_DIR))

from stream_utils import _skip_field, _varint  # noqa: E402
from work_with_prepared_data.radiobioligy_project.survival.plot_geant4_proton_beam_geometry import (  # noqa: E402
    DEFAULT_CT_DIR,
    DEFAULT_RS,
    geometry_and_contours,
)
from work_with_prepared_data.radiobioligy_project.utils.plotting_helpers import (  # noqa: E402
    MatplotlibConfigurator,
)


DEFAULT_RUN_ROOT = (
    TASK_DIR / "scoring_v2_proton_100MeV_L_to_R_reduced_10k"
)
DEFAULT_OUTPUT = (
    TASK_DIR
    / "outputs"
    / "geant4_livermore_20260724"
    / "proton_100MeV_reduced_10k"
)

NX = 128
NY = 128
NZ = 199
PX_MM = 0.4
PY_MM = 0.4
PZ_MM = 0.2
HISTORIES = 10_000
CENTRAL_RADIUS_MM = 5.0
BEAM_RADIUS_MM = 14.4
SMOOTHING_BINS = 5
COMPONENTS = (
    "electron",
    "hydrogen",
    "helium",
    "ion_Z3_to_Z6",
    "ion_Z7_plus",
    "primary_C12",
)


def is_scanned_plan(case: str) -> bool:
    return case.startswith("makerP") or case.startswith("g38")


def case_thickness_mm(case: str) -> float:
    if is_scanned_plan(case):
        return float("nan")
    if case == "through":
        return 0.0
    match = re.fullmatch(r"peak(\d+(?:p\d+)?)", case)
    if match is None:
        raise ValueError(f"Unrecognised proton case: {case}")
    return float(match.group(1).replace("p", "."))


def case_label(case: str) -> str:
    if case.startswith("g38"):
        if "powerlaw" in case:
            return r"g38: $\sigma(E)=4{,}0$–$5{,}2$ мм"
        if "fixed5p0" in case:
            return r"g38: $\sigma=5{,}0$ мм"
        return "план g38"
    thickness = case_thickness_mm(case)
    if np.isnan(thickness):
        medium = "воздух" if "_air_" in case else "вакуум"
        return f"makerP ({medium})"
    if thickness == 0.0:
        return "прострел"
    return f"пик ({thickness:g} мм ПММА)"


def case_short_label(case: str) -> str:
    if case.startswith("g38"):
        if "powerlaw" in case:
            return r"$\sigma(E)$"
        if "fixed5p0" in case:
            return r"$\sigma=5{,}0$ мм"
        return "g38"
    if case.startswith("makerP"):
        return "makerP"
    thickness = case_thickness_mm(case)
    if thickness == 0.0:
        return "прострел"
    return f"{thickness:g} мм"


def rasterise_gtv(contours: list[np.ndarray]) -> np.ndarray:
    """Return mask indexed as [z, DICOM row, DICOM column]."""
    mask = np.zeros((NZ, NX, NY), dtype=bool)
    for contour in contours:
        iz = int(round(float(np.mean(contour[:, 2])) / PZ_MM - 0.5))
        if iz < 0 or iz >= NZ:
            continue
        image = Image.new("1", (NY, NX), 0)
        polygon = [
            (
                float(point[0] / PY_MM - 0.5),
                float(point[1] / PX_MM - 0.5),
            )
            for point in contour
        ]
        ImageDraw.Draw(image).polygon(polygon, outline=1, fill=1)
        mask[iz] |= np.asarray(image, dtype=bool)
    return mask


def gtv_geometry(
    ct_dir: Path,
    rs_path: Path,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, tuple[float, float]]:
    """Build GTV lookup arrays in Geant4 voxel-ID order."""
    _, _, _, contours, _ = geometry_and_contours(ct_dir, rs_path)
    image_mask = rasterise_gtv(contours)

    # DICOM row -> Geant4 x and DICOM column -> Geant4 y.  A flattened
    # Geant4 voxel map has x as the fastest index.
    geant_mask = np.transpose(image_mask, (0, 2, 1))
    flat_mask = geant_mask.ravel()
    gtv_ids = np.flatnonzero(flat_mask)
    gtv_lookup = np.full(NX * NY * NZ, -1, dtype=np.int32)
    gtv_lookup[gtv_ids] = np.arange(gtv_ids.size, dtype=np.int32)

    iy = (gtv_ids // NX) % NY
    depth = (NY - iy.astype(float) - 0.5) * PY_MM
    depth_interval = (float(np.min(depth)), float(np.max(depth)))
    return flat_mask, gtv_ids, gtv_lookup, depth_interval


def find_main_map(case_dir: Path) -> Path:
    matches = [
        path
        for path in case_dir.glob("vox_*_0")
        if "_component_" not in path.name
    ]
    if len(matches) != 1:
        raise RuntimeError(
            f"Expected one main voxel map in {case_dir}, found {len(matches)}"
        )
    return matches[0]


def parse_voxel_map(
    path: Path,
    gtv_lookup: np.ndarray,
    *,
    include_dose: bool,
) -> dict[str, np.ndarray | int]:
    """Stream a totDoseVoxelMap without materialising all protobuf objects."""
    gtv_count = int(np.count_nonzero(gtv_lookup >= 0))
    gtv_energy = np.zeros(gtv_count, dtype=float)
    gtv_energy2 = np.zeros(gtv_count, dtype=float)
    gtv_let_base = np.zeros(gtv_count, dtype=float)
    gtv_dose = np.zeros(gtv_count, dtype=float)
    depth_energy = np.zeros(NY, dtype=float)
    central_energy = np.zeros(NY, dtype=float)
    central_let_base = np.zeros(NY, dtype=float)
    entry_count = 0

    with path.open("rb") as handle:
        while True:
            try:
                tag = _varint(handle)
            except EOFError:
                break
            field, wire = tag >> 3, tag & 7
            if field != 1 or wire != 2:
                _skip_field(handle, wire)
                continue

            entry_length = _varint(handle)
            entry_end = handle.tell() + entry_length
            voxel_id: int | None = None
            dep_energy = 0.0
            dep_energy2 = 0.0
            let_base = 0.0
            dose = 0.0
            while handle.tell() < entry_end:
                entry_tag = _varint(handle)
                entry_field, entry_wire = entry_tag >> 3, entry_tag & 7
                if entry_field == 1 and entry_wire == 0:
                    voxel_id = _varint(handle)
                elif entry_field == 2 and entry_wire == 2:
                    value_length = _varint(handle)
                    value_end = handle.tell() + value_length
                    while handle.tell() < value_end:
                        value_tag = _varint(handle)
                        value_field, value_wire = value_tag >> 3, value_tag & 7
                        if value_field == 2 and value_wire == 1:
                            dep_energy = struct.unpack(
                                "<d", handle.read(8)
                            )[0]
                        elif value_field == 3 and value_wire == 1:
                            dep_energy2 = struct.unpack(
                                "<d", handle.read(8)
                            )[0]
                        elif value_field == 4 and value_wire == 1:
                            let_base = struct.unpack(
                                "<d", handle.read(8)
                            )[0]
                        elif (
                            include_dose
                            and value_field == 9
                            and value_wire == 1
                        ):
                            dose = struct.unpack("<d", handle.read(8))[0]
                        else:
                            _skip_field(handle, value_wire)
                    handle.seek(value_end)
                else:
                    _skip_field(handle, entry_wire)
            handle.seek(entry_end)

            if voxel_id is None or dep_energy <= 0.0:
                continue
            entry_count += 1
            ix = voxel_id % NX
            iy = (voxel_id // NX) % NY
            iz = voxel_id // (NX * NY)
            depth_index = NY - 1 - iy
            depth_energy[depth_index] += dep_energy

            x_mm = (ix + 0.5 - NX / 2.0) * PX_MM
            z_mm = (iz + 0.5 - NZ / 2.0) * PZ_MM
            if x_mm * x_mm + z_mm * z_mm <= CENTRAL_RADIUS_MM**2:
                central_energy[depth_index] += dep_energy
                central_let_base[depth_index] += let_base

            if 0 <= voxel_id < gtv_lookup.size:
                gtv_index = int(gtv_lookup[voxel_id])
                if gtv_index >= 0:
                    gtv_energy[gtv_index] += dep_energy
                    gtv_energy2[gtv_index] += dep_energy2
                    gtv_let_base[gtv_index] += let_base
                    if include_dose:
                        gtv_dose[gtv_index] += dose

    return {
        "entry_count": entry_count,
        "gtv_energy_keV": gtv_energy,
        "gtv_energy2_keV2": gtv_energy2,
        "gtv_let_base_keV2_um": gtv_let_base,
        "gtv_dose_Gy": gtv_dose,
        "depth_energy_keV": depth_energy,
        "central_energy_keV": central_energy,
        "central_let_base_keV2_um": central_let_base,
    }


def dose_at_volume(dose: np.ndarray, volume_percent: float) -> float:
    """Dx: minimum dose received by x% of ROI volume."""
    return float(np.percentile(dose, 100.0 - volume_percent))


def locally_aggregate_gtv_dose(
    dose: np.ndarray,
    gtv_ids: np.ndarray,
    factors: tuple[int, int, int] = (2, 2, 2),
) -> tuple[np.ndarray, int]:
    """Average dose in local blocks and retain volume weighting.

    Only fine voxels belonging to GTVp contribute to a boundary block.
    Repeating each block mean by its number of fine GTV voxels preserves the
    ROI volume weights used for Dx percentiles.
    """
    factor_x, factor_y, factor_z = factors
    ix = gtv_ids % NX
    iy = (gtv_ids // NX) % NY
    iz = gtv_ids // (NX * NY)
    blocks_x = (NX + factor_x - 1) // factor_x
    blocks_y = (NY + factor_y - 1) // factor_y
    block_id = (
        ix // factor_x
        + blocks_x * (iy // factor_y)
        + blocks_x * blocks_y * (iz // factor_z)
    )
    _, inverse = np.unique(block_id, return_inverse=True)
    counts = np.bincount(inverse)
    sums = np.bincount(inverse, weights=dose)
    means = sums / counts
    volume_weighted = np.repeat(means, counts)
    return volume_weighted, int(means.size)


def smooth(values: np.ndarray) -> np.ndarray:
    kernel = np.ones(SMOOTHING_BINS, dtype=float) / SMOOTHING_BINS
    return np.convolve(values, kernel, mode="same")


def analyse_case(
    case: str,
    case_dir: Path,
    gtv_ids: np.ndarray,
    gtv_lookup: np.ndarray,
    gtv_depth_interval: tuple[float, float],
    histories: int,
    configuration_label: str | None = None,
    beam_radius_mm: float = BEAM_RADIUS_MM,
) -> tuple[
    dict[str, float | int | str],
    dict[str, np.ndarray],
    list[dict[str, float | str]],
]:
    main_path = find_main_map(case_dir)
    thickness = case_thickness_mm(case)
    main = parse_voxel_map(main_path, gtv_lookup, include_dose=True)
    energy = np.asarray(main["gtv_energy_keV"])
    energy2 = np.asarray(main["gtv_energy2_keV2"])
    let_base = np.asarray(main["gtv_let_base_keV2_um"])
    dose = np.asarray(main["gtv_dose_Gy"])
    positive_dose = dose > 0.0
    positive_energy = energy > 0.0
    voxel_rel_se = np.full(energy.shape, np.nan, dtype=float)
    if histories > 1:
        variance_numerator = np.maximum(
            histories * energy2 - energy * energy,
            0.0,
        )
        voxel_rel_se[positive_energy] = (
            np.sqrt(
                variance_numerator[positive_energy]
                / (histories - 1.0)
            )
            / energy[positive_energy]
        )
    finite_voxel_rel_se = voxel_rel_se[np.isfinite(voxel_rel_se)]

    total_gtv_energy = float(np.sum(energy))
    total_gtv_let_base = float(np.sum(let_base))
    total_phantom_energy = float(np.sum(main["depth_energy_keV"]))
    mean_dose = float(np.mean(dose))
    dose_std = float(np.std(dose))
    d2 = dose_at_volume(dose, 2.0)
    d50 = dose_at_volume(dose, 50.0)
    d90 = dose_at_volume(dose, 90.0)
    d95 = dose_at_volume(dose, 95.0)
    d98 = dose_at_volume(dose, 98.0)
    aggregation_results: dict[str, tuple[np.ndarray, int]] = {}
    for label, factors in (
        ("0p8x0p8x0p4", (2, 2, 2)),
        ("1p2x1p2x0p6", (3, 3, 3)),
        ("1p6x1p6x0p8", (4, 4, 4)),
    ):
        aggregation_results[label] = locally_aggregate_gtv_dose(
            dose,
            gtv_ids,
            factors,
        )

    central = np.asarray(main["central_energy_keV"])
    central_smoothed = smooth(central)
    depth_mm = (np.arange(NY, dtype=float) + 0.5) * PY_MM
    peak_index = int(np.argmax(central_smoothed))
    peak_depth = float(depth_mm[peak_index])
    gtv_low, gtv_high = gtv_depth_interval
    support_mask = central_smoothed >= 0.01 * float(np.max(central_smoothed))
    distal_support_depth = float(np.max(depth_mm[support_mask]))

    gtv_ix = gtv_ids % NX
    gtv_iy = (gtv_ids // NX) % NY
    gtv_iz = gtv_ids // (NX * NY)
    gtv_x_mm = (gtv_ix + 0.5 - NX / 2.0) * PX_MM
    gtv_z_mm = (gtv_iz + 0.5 - NZ / 2.0) * PZ_MM
    gtv_depth_mm = (NY - gtv_iy - 0.5) * PY_MM
    is_makerp = is_scanned_plan(case)
    inside_beam = (
        np.ones(gtv_ids.size, dtype=bool)
        if is_makerp
        else (
            gtv_x_mm * gtv_x_mm + gtv_z_mm * gtv_z_mm
            <= beam_radius_mm**2
        )
    )
    proximal_to_distal_support = gtv_depth_mm <= distal_support_depth

    row: dict[str, float | int | str] = {
        "case": case,
        "configuration": (
            (
                "g38Gy_f1fx, 709 пятен, 73,43–100,39 МэВ"
                if case.startswith("g38")
                else "makerP, 199 источников, 16–51 МэВ"
            )
            if is_makerp
            else (
                "100 МэВ, без ПММА"
                if thickness == 0.0
                else f"100 МэВ + {thickness:g} мм ПММА"
            )
        ),
        "pmma_thickness_mm": thickness,
        "histories": histories,
        "grid": f"{NX}x{NY}x{NZ}",
        "voxel_mm": f"{PX_MM}x{PY_MM}x{PZ_MM}",
        "gtv_voxels": int(gtv_ids.size),
        "gtv_volume_mm3": float(
            gtv_ids.size * PX_MM * PY_MM * PZ_MM
        ),
        "gtv_nonzero_dose_voxels": int(np.count_nonzero(positive_dose)),
        "gtv_nonzero_dose_fraction": float(np.mean(positive_dose)),
        "gtv_nonzero_energy_fraction": float(np.mean(positive_energy)),
        "gtv_positive_voxel_rel_se_median": (
            float(np.median(finite_voxel_rel_se))
            if finite_voxel_rel_se.size
            else np.nan
        ),
        "gtv_positive_voxel_rel_se_p90": (
            float(np.percentile(finite_voxel_rel_se, 90.0))
            if finite_voxel_rel_se.size
            else np.nan
        ),
        "gtv_positive_voxels_rel_se_le_50pct_fraction": (
            float(np.mean(finite_voxel_rel_se <= 0.50))
            if finite_voxel_rel_se.size
            else np.nan
        ),
        "gtv_positive_voxels_rel_se_le_20pct_fraction": (
            float(np.mean(finite_voxel_rel_se <= 0.20))
            if finite_voxel_rel_se.size
            else np.nan
        ),
        "gtv_fraction_inside_nominal_beam_cylinder": (
            np.nan if is_makerp else float(np.mean(inside_beam))
        ),
        "central_1pct_support_distal_depth_mm": distal_support_depth,
        "gtv_fraction_distal_to_central_1pct_support": float(
            np.mean(~proximal_to_distal_support)
        ),
        "gtv_fraction_inside_beam_and_proximal_to_1pct_support": float(
            np.mean(inside_beam & proximal_to_distal_support)
        ),
        "gtv_depenergy_MeV_per_primary": (
            total_gtv_energy / 1000.0 / histories
        ),
        "gtv_energy_fraction_of_phantom": (
            total_gtv_energy / total_phantom_energy
            if total_phantom_energy > 0.0
            else np.nan
        ),
        "gtv_mean_dose_Gy_per_run": mean_dose,
        "gtv_mean_dose_Gy_per_primary": mean_dose / histories,
        "gtv_dose_cv": (
            dose_std / mean_dose if mean_dose > 0.0 else np.nan
        ),
        "gtv_D2_Gy_per_run": d2,
        "gtv_D50_Gy_per_run": d50,
        "gtv_D90_Gy_per_run": d90,
        "gtv_D95_Gy_per_run": d95,
        "gtv_D98_Gy_per_run": d98,
        "gtv_D2_over_Dmean": d2 / mean_dose if mean_dose > 0 else np.nan,
        "gtv_D50_over_Dmean": d50 / mean_dose if mean_dose > 0 else np.nan,
        "gtv_D90_over_Dmean": d90 / mean_dose if mean_dose > 0 else np.nan,
        "gtv_D95_over_Dmean": d95 / mean_dose if mean_dose > 0 else np.nan,
        "gtv_D98_over_Dmean": d98 / mean_dose if mean_dose > 0 else np.nan,
        "gtv_LETd_w_keV_um": (
            total_gtv_let_base / total_gtv_energy
            if total_gtv_energy > 0.0
            else np.nan
        ),
        "central_peak_band_LETd_w_keV_um": np.nan,
        "central_gtv_depth_LETd_w_keV_um": np.nan,
        "central_peak_depth_mm": peak_depth,
        "central_peak_inside_gtv_depth_interval": int(
            gtv_low <= peak_depth <= gtv_high
        ),
        "gtv_depth_min_mm_from_plus_y_surface": gtv_low,
        "gtv_depth_max_mm_from_plus_y_surface": gtv_high,
        "main_map_entries": int(main["entry_count"]),
        "main_voxel_map": str(main_path),
    }
    if configuration_label:
        row["configuration"] = configuration_label
    for label, (aggregated_dose, aggregated_voxels) in (
        aggregation_results.items()
    ):
        aggregated_d2 = dose_at_volume(aggregated_dose, 2.0)
        aggregated_d50 = dose_at_volume(aggregated_dose, 50.0)
        aggregated_d90 = dose_at_volume(aggregated_dose, 90.0)
        aggregated_d95 = dose_at_volume(aggregated_dose, 95.0)
        aggregated_d98 = dose_at_volume(aggregated_dose, 98.0)
        row[f"gtv_aggregated_voxels_{label}"] = aggregated_voxels
        row[f"gtv_aggregated_nonzero_volume_fraction_{label}"] = float(
            np.mean(aggregated_dose > 0.0)
        )
        row[f"gtv_aggregated_D2_over_Dmean_{label}"] = (
            aggregated_d2 / mean_dose
            if mean_dose > 0.0
            else np.nan
        )
        row[f"gtv_aggregated_D50_over_Dmean_{label}"] = (
            aggregated_d50 / mean_dose
            if mean_dose > 0.0
            else np.nan
        )
        row[f"gtv_aggregated_D90_over_Dmean_{label}"] = (
            aggregated_d90 / mean_dose
            if mean_dose > 0.0
            else np.nan
        )
        row[f"gtv_aggregated_D95_over_Dmean_{label}"] = (
            aggregated_d95 / mean_dose
            if mean_dose > 0.0
            else np.nan
        )
        row[f"gtv_aggregated_D98_over_Dmean_{label}"] = (
            aggregated_d98 / mean_dose
            if mean_dose > 0.0
            else np.nan
        )
        row[f"gtv_aggregated_HI98_{label}"] = (
            (aggregated_d2 - aggregated_d98) / aggregated_d50
            if aggregated_d50 > 0.0
            else np.nan
        )

    central_let_base = np.asarray(main["central_let_base_keV2_um"])
    peak_band = np.abs(depth_mm - peak_depth) <= 1.0
    gtv_depth_band = (depth_mm >= gtv_low) & (depth_mm <= gtv_high)
    peak_band_energy = float(np.sum(central[peak_band]))
    gtv_depth_energy = float(np.sum(central[gtv_depth_band]))
    row["central_peak_band_LETd_w_keV_um"] = (
        float(np.sum(central_let_base[peak_band])) / peak_band_energy
        if peak_band_energy > 0.0
        else np.nan
    )
    row["central_gtv_depth_LETd_w_keV_um"] = (
        float(np.sum(central_let_base[gtv_depth_band])) / gtv_depth_energy
        if gtv_depth_energy > 0.0
        else np.nan
    )

    component_rows: list[dict[str, float | str]] = []
    for component in COMPONENTS:
        component_matches = list(
            case_dir.glob(f"*_component_{component}_0")
        )
        if not component_matches:
            continue
        component_data = parse_voxel_map(
            component_matches[0],
            gtv_lookup,
            include_dose=False,
        )
        component_energy = float(
            np.sum(component_data["gtv_energy_keV"])
        )
        component_let_base = float(
            np.sum(component_data["gtv_let_base_keV2_um"])
        )
        component_rows.append(
            {
                "case": case,
                "component": component,
                "gtv_depenergy_MeV_per_primary": (
                    component_energy / 1000.0 / histories
                ),
                "fraction_of_total_gtv_depenergy": (
                    component_energy / total_gtv_energy
                    if total_gtv_energy > 0.0
                    else np.nan
                ),
                "component_gtv_LETd_w_keV_um": (
                    component_let_base / component_energy
                    if component_energy > 0.0
                    else np.nan
                ),
            }
        )

    # Cumulative DVH: volume receiving at least the stated dose/Dmean.
    # Keep the fine-grid curve and the three volume-weighted local
    # aggregations on one shared dose grid so their statistical-resolution
    # dependence can be compared without interpolation.
    dose_distributions = {
        "fine_grid": dose,
        **{
            label: aggregated_dose
            for label, (aggregated_dose, _) in aggregation_results.items()
        },
    }
    normalised_distributions = {
        label: (
            values / mean_dose if mean_dose > 0.0 else values
        )
        for label, values in dose_distributions.items()
    }
    max_ratio = max(
        3.0,
        *(
            float(np.percentile(values, 99.5))
            for values in normalised_distributions.values()
        ),
    )
    dose_ratio_grid = np.linspace(0.0, max_ratio, 301)
    volume_receiving_by_resolution = {
        label: np.array(
            [
                100.0 * np.mean(values >= threshold)
                for threshold in dose_ratio_grid
            ]
        )
        for label, values in normalised_distributions.items()
    }

    central_let_base = np.asarray(main["central_let_base_keV2_um"])
    central_letd = np.divide(
        central_let_base,
        central,
        out=np.full_like(central, np.nan, dtype=float),
        where=central > 0.0,
    )
    central_letd_smoothed = np.divide(
        smooth(central_let_base),
        central_smoothed,
        out=np.full_like(central_smoothed, np.nan, dtype=float),
        where=central_smoothed > 0.0,
    )
    profiles = {
        "depth_mm": depth_mm,
        "central_energy_keV": central,
        "central_energy_smoothed_keV": central_smoothed,
        "central_let_base_keV2_um": central_let_base,
        "central_LETd_w_keV_um": central_letd,
        "central_LETd_w_smoothed_keV_um": central_letd_smoothed,
        "dose_over_mean_grid": dose_ratio_grid,
        "volume_receiving_percent": (
            volume_receiving_by_resolution["fine_grid"]
        ),
        **{
            f"volume_receiving_percent_{label}": values
            for label, values in volume_receiving_by_resolution.items()
            if label != "fine_grid"
        },
    }
    return row, profiles, component_rows


def write_dict_rows(path: Path, rows: list[dict]) -> None:
    if not rows:
        return
    with path.open("w", newline="", encoding="utf-8-sig") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def write_profiles(
    output_dir: Path,
    profiles_by_case: dict[str, dict[str, np.ndarray]],
) -> None:
    for case, profiles in profiles_by_case.items():
        depth_path = output_dir / f"{case}_central_depth_profile.csv"
        with depth_path.open("w", newline="", encoding="utf-8-sig") as handle:
            writer = csv.writer(handle)
            writer.writerow(
                (
                    "depth_mm_from_plus_y_surface",
                    "central_energy_keV",
                    "central_energy_smoothed_keV",
                    "central_let_base_keV2_um",
                    "central_LETd_w_keV_um",
                    "central_LETd_w_smoothed_keV_um",
                )
            )
            for values in zip(
                profiles["depth_mm"],
                profiles["central_energy_keV"],
                profiles["central_energy_smoothed_keV"],
                profiles["central_let_base_keV2_um"],
                profiles["central_LETd_w_keV_um"],
                profiles["central_LETd_w_smoothed_keV_um"],
            ):
                writer.writerow(values)

        dvh_path = output_dir / f"{case}_normalised_dvh.csv"
        with dvh_path.open("w", newline="", encoding="utf-8-sig") as handle:
            writer = csv.writer(handle)
            aggregation_labels = (
                "0p8x0p8x0p4",
                "1p2x1p2x0p6",
                "1p6x1p6x0p8",
            )
            writer.writerow(
                (
                    "dose_over_gtv_mean",
                    "volume_receiving_percent",
                    *(
                        f"volume_receiving_percent_{label}"
                        for label in aggregation_labels
                    ),
                )
            )
            writer.writerows(
                zip(
                    profiles["dose_over_mean_grid"],
                    profiles["volume_receiving_percent"],
                    *(
                        profiles[f"volume_receiving_percent_{label}"]
                        for label in aggregation_labels
                    ),
                )
            )


def plot_results(
    rows: list[dict[str, float | int | str]],
    profiles_by_case: dict[str, dict[str, np.ndarray]],
    component_rows: list[dict[str, float | str]],
    output_stem: Path,
    figure_title: str | None = None,
    single_case_label: str | None = None,
    marker_component: str = "hydrogen",
    marker_component_label: str = "H-компонента",
) -> None:
    configurator = MatplotlibConfigurator()
    configurator.apply_custom_styles()
    try:
        plt.rcParams.update(
            {
                "font.size": 11,
                "axes.titlesize": 13,
                "axes.labelsize": 12,
                "legend.fontsize": 10,
            }
        )
        fig, axes = plt.subplots(
            2,
            2,
            figsize=(12.5, 9.0),
            constrained_layout=True,
        )
        ax_depth, ax_dvh, ax_dose, ax_let = axes.ravel()
        cases = [str(row["case"]) for row in rows]
        colour_values = plt.cm.viridis(
            np.linspace(0.08, 0.88, len(cases))
        )
        colours = dict(zip(cases, colour_values))
        labels = {case: case_label(case) for case in cases}
        short_labels = {case: case_short_label(case) for case in cases}
        if single_case_label is not None and len(cases) == 1:
            labels[cases[0]] = single_case_label
            short_labels[cases[0]] = single_case_label
        coverage_labels = {
            str(row["case"]): (
                f"{short_labels[str(row['case'])]}\n"
                f"({100.0 * float(row['gtv_nonzero_dose_fraction']):.1f}%)"
            )
            for row in rows
        }

        gtv_low = float(rows[0]["gtv_depth_min_mm_from_plus_y_surface"])
        gtv_high = float(rows[0]["gtv_depth_max_mm_from_plus_y_surface"])
        ax_depth.axvspan(
            gtv_low,
            gtv_high,
            color="#e31a1c",
            alpha=0.10,
            label="аксиальный интервал GTVp",
        )
        for row in rows:
            case = str(row["case"])
            profile = profiles_by_case[case]
            smoothed = profile["central_energy_smoothed_keV"]
            normalised = smoothed / np.max(smoothed)
            ax_depth.plot(
                profile["depth_mm"],
                normalised,
                color=colours[case],
                linewidth=2.2,
                label=labels[case],
            )
            ax_depth.axvline(
                float(row["central_peak_depth_mm"]),
                color=colours[case],
                linestyle=":",
                linewidth=1.3,
            )
        ax_depth.set(
            xlabel=(
                "Глубина вдоль пучка, мм\n"
                "(0 = входная граница воксельного фантома)"
            ),
            ylabel="Нормированный энерговклад",
            title=(
                "Центральный профиль вдоль направления пучка"
                if figure_title is not None
                else "Профиль внутри фантома; ПММА находится перед x=0"
            ),
            xlim=(0.0, NY * PY_MM),
            ylim=(0.0, 1.08),
        )
        ax_depth.annotate(
            "направление пучка",
            xy=(12.0, 1.035),
            xytext=(2.0, 1.035),
            arrowprops={"arrowstyle": "->", "color": "0.3"},
            ha="left",
            va="center",
            color="0.3",
            fontsize=9,
        )
        ax_depth.grid(alpha=0.22)
        ax_depth.legend(frameon=True)

        for row_index, row in enumerate(rows):
            case = str(row["case"])
            profile = profiles_by_case[case]
            ax_dvh.plot(
                profile["dose_over_mean_grid"],
                profile["volume_receiving_percent"],
                color=colours[case],
                linewidth=1.3,
                linestyle=":",
                alpha=0.72,
                label=f"{labels[case]} — исходная сетка",
            )
            ax_dvh.plot(
                profile["dose_over_mean_grid"],
                profile["volume_receiving_percent_1p6x1p6x0p8"],
                color=colours[case],
                linewidth=2.3,
                label=f"{labels[case]} — 1,6×1,6×0,8 мм",
            )
            d90 = float(
                row["gtv_aggregated_D90_over_Dmean_1p6x1p6x0p8"]
            )
            ax_dvh.scatter(
                [d90],
                [90.0],
                s=34,
                color=colours[case],
                edgecolor="white",
                linewidth=0.7,
                zorder=4,
            )
            ax_dvh.annotate(
                f"{d90:.2f}",
                (d90, 90.0),
                xytext=(8, 8 - 15 * row_index),
                textcoords="offset points",
                color=colours[case],
                fontsize=9,
            )
        ax_dvh.axhline(90.0, color="0.45", linestyle="--", linewidth=1.0)
        ax_dvh.axvline(1.0, color="0.45", linestyle=":", linewidth=1.0)
        ax_dvh.set(
            xlabel=r"Доза в вокселе / $D_{\mathrm{mean}}$ GTVp",
            ylabel="Объём GTVp, получивший ≥ дозы, %",
            title="Нормированная DVH: исходная и отчётная сетки",
            xlim=(0.0, 3.0),
            ylim=(0.0, 102.0),
        )
        ax_dvh.grid(alpha=0.22)
        ax_dvh.legend(frameon=True)

        x = np.arange(len(cases))
        d90_ratio = np.asarray(
            [
                float(
                    row[
                        "gtv_aggregated_D90_over_Dmean_1p6x1p6x0p8"
                    ]
                )
                for row in rows
            ]
        )
        d50_ratio = np.asarray(
            [
                float(
                    row[
                        "gtv_aggregated_D50_over_Dmean_1p6x1p6x0p8"
                    ]
                )
                for row in rows
            ]
        )
        width = 0.34
        d90_bars = ax_dose.bar(
            x - width / 2,
            d90_ratio,
            width,
            color="#67a9cf",
            label=r"$D_{90}/D_{\mathrm{mean}}$",
        )
        d50_bars = ax_dose.bar(
            x + width / 2,
            d50_ratio,
            width,
            color="#ef8a62",
            label=r"$D_{50}/D_{\mathrm{mean}}$",
        )
        ax_dose.set_xticks(x, [coverage_labels[case] for case in cases])
        ax_dose.set(
            ylabel="Относительная доза",
            title="Покрытие GTVp: локальное усреднение 1,6×1,6×0,8 мм",
            ylim=(0.0, max(1.1, float(np.nanmax(d50_ratio)) * 1.15)),
        )
        ax_dose.grid(axis="y", alpha=0.22)
        ax_dose.legend(frameon=True)
        ax_dose.bar_label(d90_bars, fmt="%.2f", padding=3, fontsize=9)
        ax_dose.bar_label(d50_bars, fmt="%.2f", padding=3, fontsize=9)

        total_let = np.asarray(
            [float(row["gtv_LETd_w_keV_um"]) for row in rows]
        )
        ax_let.bar(
            x,
            total_let,
            width=0.55,
            color=[colours[case] for case in cases],
            alpha=0.86,
            label="полный энерговклад",
        )
        marker_by_case = {
            str(row["case"]): float(row["component_gtv_LETd_w_keV_um"])
            for row in component_rows
            if str(row["component"]) == marker_component
        }
        marker_let = np.asarray(
            [marker_by_case.get(case, np.nan) for case in cases]
        )
        ax_let.scatter(
            x,
            marker_let,
            s=65,
            marker="D",
            color="#7b3294",
            label=marker_component_label,
            zorder=3,
        )
        ax_let.set_xticks(x, [short_labels[case] for case in cases])
        ax_let.set(
            ylabel="Дозо-взвешенная ЛПЭ, кэВ/мкм",
            title="ЛПЭ внутри GTVp",
            ylim=(
                0.0,
                max(
                    float(np.nanmax(total_let)),
                    (
                        float(np.nanmax(marker_let))
                        if np.any(np.isfinite(marker_let))
                        else 0.0
                    ),
                )
                * 1.18,
            ),
        )
        ax_let.grid(axis="y", alpha=0.22)
        ax_let.legend(frameon=True)

        fig.suptitle(
            figure_title
            if figure_title is not None
            else (
                (
                    "Экспериментальный сканирующий план g38Gy_f1fx "
                    "с 40 мм ПММА в воксельном фантоме крысы"
                    if any(case.startswith("g38") for case in cases)
                    else (
                        "Авторское многокомпонентное протонное поле makerP "
                        "в воксельном фантоме крысы"
                    )
                )
                if any(is_scanned_plan(case) for case in cases)
                else (
                    "Протоны 100 МэВ в воксельном фантоме крысы: "
                    "прострел и формирование пика ПММА"
                )
            ),
            fontsize=15,
        )
        for suffix in (".png", ".svg", ".pdf"):
            fig.savefig(output_stem.with_suffix(suffix), dpi=300)
        plt.close(fig)
    finally:
        configurator.restore_original_styles()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--run-root", type=Path, default=DEFAULT_RUN_ROOT)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--ct-dir", type=Path, default=DEFAULT_CT_DIR)
    parser.add_argument("--rtstruct", type=Path, default=DEFAULT_RS)
    parser.add_argument("--histories", type=int, default=HISTORIES)
    parser.add_argument(
        "--configuration-label",
        help="Optional label written to the numerical result table.",
    )
    parser.add_argument(
        "--figure-title",
        help="Optional title replacing the proton-specific plot title.",
    )
    parser.add_argument(
        "--single-case-label",
        help="Optional display label when exactly one case is plotted.",
    )
    parser.add_argument(
        "--plot-stem",
        help="Optional output stem replacing the proton-specific file name.",
    )
    parser.add_argument(
        "--plot-preset",
        choices=("carbon-target", "gamma"),
        help="Optional radiation-specific labels for a reused analysis.",
    )
    parser.add_argument(
        "--beam-radius-mm",
        type=float,
        default=BEAM_RADIUS_MM,
        help="Nominal circular-field radius used for geometric GTV coverage.",
    )
    parser.add_argument(
        "--skip-plots",
        action="store_true",
        help=(
            "Write numerical tables and profiles without the "
            "proton-specific comparison figure."
        ),
    )
    parser.add_argument(
        "--cases",
        nargs="+",
        default=("through", "peak55"),
    )
    args = parser.parse_args()
    if args.plot_preset == "carbon-target":
        args.figure_title = (
            "Ионы углерода: проектный расширенный пик "
            "в воксельном фантоме крысы"
        )
        args.single_case_label = "проектный углеродный пик"
    elif args.plot_preset == "gamma":
        args.figure_title = (
            args.figure_title
            or "Гамма-излучение Co-60 в воксельном фантоме крысы"
        )
        args.single_case_label = args.single_case_label or "Co-60"

    args.output_dir.mkdir(parents=True, exist_ok=True)
    _, gtv_ids, gtv_lookup, depth_interval = gtv_geometry(
        args.ct_dir,
        args.rtstruct,
    )
    rows: list[dict[str, float | int | str]] = []
    profiles_by_case: dict[str, dict[str, np.ndarray]] = {}
    all_component_rows: list[dict[str, float | str]] = []
    for case in args.cases:
        row, profiles, component_rows = analyse_case(
            case,
            args.run_root / case,
            gtv_ids,
            gtv_lookup,
            depth_interval,
            args.histories,
            args.configuration_label,
            args.beam_radius_mm,
        )
        rows.append(row)
        profiles_by_case[case] = profiles
        all_component_rows.extend(component_rows)

    write_dict_rows(args.output_dir / "gtv_summary.csv", rows)
    write_dict_rows(
        args.output_dir / "gtv_component_breakdown.csv",
        all_component_rows,
    )
    write_profiles(args.output_dir, profiles_by_case)
    plot_stem = args.plot_stem or (
        (
            "proton_g38_plan_gtv"
            if all(str(row["case"]).startswith("g38") for row in rows)
            else "proton_makerP_gtv"
        )
        if all(is_scanned_plan(str(row["case"])) for row in rows)
        else "proton_100MeV_gtv_comparison"
    )
    if not args.skip_plots:
        plot_results(
            rows,
            profiles_by_case,
            all_component_rows,
            args.output_dir / plot_stem,
            args.figure_title,
            args.single_case_label,
            (
                "electron"
                if args.plot_preset == "gamma"
                else "hydrogen"
            ),
            (
                "электронная компонента"
                if args.plot_preset == "gamma"
                else "H-компонента"
            ),
        )

    print(f"output={args.output_dir}")
    print(
        f"GTVp: {len(gtv_ids)} voxels, "
        f"{len(gtv_ids) * PX_MM * PY_MM * PZ_MM:.2f} mm3, "
        f"depth={depth_interval[0]:.2f}..{depth_interval[1]:.2f} mm"
    )
    for row in rows:
        print(
            f"{row['case']}: peak={row['central_peak_depth_mm']:.2f} mm, "
            f"D90/Dmean={row['gtv_D90_over_Dmean']:.4f}, "
            f"D50/Dmean={row['gtv_D50_over_Dmean']:.4f}, "
            f"coverage={100.0 * float(row['gtv_nonzero_dose_fraction']):.2f}%, "
            f"LETd,w={row['gtv_LETd_w_keV_um']:.4f} keV/um"
        )


if __name__ == "__main__":
    main()
